sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: eu/dkja+Yw10hMR7Koq3Ae9+nv1ohFzot6pEs38xmaUDjNESEFiXRh9DXF7gf5D0oj3FiFGw0NRer0JhyaOefaDktYWus6DlM5G2ki5ZzY/0MESXTQr7ZvXpuEgeak0lrTG7X/R8lA9MPiWOkW9OTFA302Oz2jHmkD6nCSarMedx6Q1xza3Gl3+YWoE6uBkzGfw5EoZGmxyu0jKmYLv9os5EzDg1hdx9FAq69owNyufaDypS80l8qISPXSuRM+wSzYjzRBaUgoGdx6Z2fpGh9BRoM1+vSUNOCry9wyQysLNZUZvm/rsa1W4hR7KeTSUjgkMuQBax2AVWPg5hPZNLsemZXCgI7Ljfn2RaiSPBLD5KGz8Wx4W8lZvi5t2I1d9IIhZofO+d8ZpDNz27OcPE4nPkyb6UH4yj2CAHrbOKEm5kKxiIiPvHRPZ6IU+s1TBwx2rmmLkZ2UdxvoKnprw4zICgwePLgjJPjmY3RG915E7tr6O1qLAOoRZBVNdoQAA0GNo+fpAveNJJ3pTIk4eu9J+OGAsXzfA0T8Qk1aYYWoNo4vhh3cVM/QO5xcc5uoeU1sFvuvSsSOMYSEI+7XwCEdZC7hMIqYYn36LOVcmEJFA/tfXgbTNbGm/ipQHvdZEDUmLa/QM5j3YSbcxkMG4eyQoXalCMhAGpOiINjhFrhI8=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: RYwhmUqgF0aNi/q3zGT6tqjYzgMVUVEN++gP1OW/fWzs9nMzsgh2P2qTwFRjEtx0imOrwzwEIs0bGEWg6h8OKivNsHuNts5xJbCwYV/P9Kh08iKdyMDVhOtH8WNVCa7SGkG0SlZpWOBppPGF+w2HUr1LkA9qpnDWf4UmLRhvTYxbiyy/tZ4Rtv9n1BVuPQJokoQSrbJUrrBvreDWi196J8A0jsrLqhCTuzoEOSpF0Vx795enYubdwrVBim8RdWHaIJC/QBsIbj+zLXhy361Cn/ai19VvPS5uUsFvLDjq2jwB0KrBKgAXYpG+p881AFYuJbu9Qw6sJN4JCI5jVodiEIm7WQnw3KKMf/yJL0BCOaUJT3pKD/f7YRhWJH96jn8G/DYKXpddrzW145c+2QWqNRUiDS8LrQlih+kUBM7HhWlVnhEplP5UpHYQSyvquTiD56dX4UenUkhyNt3ilZTBpoebgYDJJx6uv6IQRgcWq6YZMx7yJqNHSQURXHwRn/1OlBnUBc7m9hBZT0ROeFZlj1f9WXKros5sWDi6XiZkFwPqe1ubWUVcvFJCVqT+E7AQWFJz47mDt+GDc5G6POpYTnlbWJpdmPSyNo9l5JuENcCCQ7QlXTSjNEi7zGMHxyjRGxWGZJZDAyvmtx75XhiuHCb2XG+qpEUe4qT43uXR5Lw=
